### ISSUE TITLE
How to configure a own mail server

### ISSUE THREAD

**Issue by marting885** [bmarsh9/gapps#98]
I need to config my mail server for sent a  new user invite ,  i cannot config in the docker-compose.yml i recieved an error  in frontend . 

Thanks 
Martin

**Comment by bmarsh9** [comment]
What have you tried so far and what error did you receive?

**Comment by marting885** [comment]
this is the error 
10.0.0.2 - - [19/Oct/2023:20:40:35 +0000] "POST /api/v1/tenants/1/invite-user HTTP/1.1" 200 319 "http://segit.snd.int:5501/users" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/email.py", line 8, in send_async_email
    mail.send(msg)
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
10.0.0.2 - - [19/Oct/2023:20:40:35 +0000] "GET /api/v1/tenants/1/users HTTP/1.1" 200 375 "http://segit.snd.int:5501/users" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
10.0.0.2 - - [19/Oct/2023:20:40:50 +0000] "POST /api/v1/tenants/1/invite-user HTTP/1.1" 200 319 "http://segit.snd.int:5501/users" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/email.py", line 8, in send_async_email
    mail.send(msg)
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

I tested by telnet in the container and i can send mail properly . 

Thanks

**Comment by bmarsh9** [comment]
@marting885 Did you configure any of the MAIL env variables [here](https://github.com/bmarsh9/gapps/blob/main/config.py#L30)? There are 5 different env variables to configure your mail server.

**Comment by marting885** [comment]
Yes,  i send it my docker compose 
![image](https://github.com/bmarsh9/gapps/assets/148495628/637c4bdb-d8d7-46cb-9e88-f17829de5912)

**Comment by bmarsh9** [comment]
Its very possible `MAIL_USE_TLS` is the issue. Its hardcoded to `True` [on this line](https://github.com/bmarsh9/gapps/blob/main/config.py#L32) so your env variable isn't picked up

**Comment by bmarsh9** [comment]
Updated the code - try pulling from Main, building the new container image and running @marting885

**Comment by marting885** [comment]
I have the same error with de TLS in FALSE 

7.0.0.0 Safari/537.36"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/email.py", line 8, in send_async_email
    mail.send(msg)
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/usr/local/lib/python3.8/dist-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

![image](https://github.com/bmarsh9/gapps/assets/148495628/ca3d1c91-29cc-40e1-beb9-06f2cfa5ed67)


have another idea , thanks for your help.

**Comment by bmarsh9** [comment]
"False" not "FALSE"

**Comment by bmarsh9** [comment]
Closing for now.. let me know if you have issues. You can also test locally with Flask-mail (which is the library that Gapps uses)
